AVAILABLE_ROLES = {
    :teacher => 'Lehrkraft',
    :schueler => 'Schülerin / Schüler',
    :otium => 'Otium',
    :admin => 'Administrator',
    :developer => 'Entwickler',
    :sekretariat => 'Sekretariat',
    :zeugnis_admin => 'Zeugnis-Admin',
    :can_see_all_timetables => 'kann alle Stundenpläne sehen',
    # :can_manage_salzh,
    :can_upload_files => 'kann Dateien hochladen',
    :can_manage_news => 'kann News verwalten',
    :can_manage_monitors => 'kann Monitore verwalten',
    :can_manage_tablets => 'kann Tabletbuchungen verwalten',
    :can_book_tablets => 'kann Tablets buchen',
    :can_use_aula => 'Aulatechnik',
    :can_manage_antikenfahrt => 'kann Antikenfahrt verwalten',
    :can_manage_agr_app => 'kann die Altgriechisch-App verwalten',
    :can_manage_bib => 'kann die Bibliothek verwalten',
    :can_manage_bib_members => 'kann Bibliotheksnutzer verwalten',
    :can_manage_bib_payment => 'kann Bibliothekszahlungen verwalten',
    :can_manage_bib_special_access => 'Bibliothek Spezialzugriff',
    :can_manage_angebote => 'kann Angebote verwalten',
    :can_manage_forschertage => 'kann Forschertage verwalten',
    :can_manage_tech_problems => 'kann gemeldete Technikprobleme bearbeiten',
    :can_manage_project_wifi_access => 'kann Zugriff auf das Projekt-WLAN verwalten',
    :can_open_project_wifi => 'kann das Projekt-WLAN öffnen',
    :externe_ag_leitung => 'AG-Leitung (extern)',
    :gev => 'GEV',
    :sv => 'Schülervertretung',
    :sv_editor => 'SV-Redaktion',
    :sv_admin => 'SV-Admin',
    :technikteam => 'Technikteam',
    :technikamt => 'Technikamt',
    :wants_to_receive_techpost_debug_mail => 'Erhält E-Mails zu Technikproblemen',
    :wants_to_receive_school_wifi_request_mail => 'Erhält E-Mails zu WLAN-Anfragen',
    :datentresor_hotline => 'kann Lehrkräfte für den Datentresor freischalten',
    :schulbuchverein => 'Schulbuchverein',
    :can_receive_messages => 'kann Nachrichten empfangen',
    :can_write_messages => 'kann Nachrichten schreiben',
    :can_create_polls => 'kann Umfragen durchführen',
    :can_create_events => 'kann Termine anlegen',
    :can_use_mailing_lists => 'kann alle Mail-Verteiler verwenden',
    :can_use_nextcloud => 'kann die Nextcloud verwenden',
    :can_use_sms_gateway => 'kann die SMS-Anmeldung benutzen',
    :can_report_tech_problems => 'kann Technikprobleme melden',
    :oko => 'Oberstufenkoordination',
    :can_manage_projekttage => 'kann Projekttage verwalten',
    :can_see_kurslisten => 'kann Kurslisten einsehen',
    :mittagessen => 'kann Bestellungen für Mittagessen einsehen',
    :praktikum => 'Praktikum (kann Stundenpläne ohne Details einsehen)',
    :can_print_photos => 'kann Fotos drucken',
    :can_manage_lab8 => 'kann Lab8-Projekte verwalten',
    :unterstufenparty => 'Unterstufenparty',
}

ROLE_TRANSITIONS = <<~END_OF_STRING
    teacher => can_receive_messages can_write_messages can_book_tablets can_create_polls can_create_events can_use_mailing_lists can_use_nextcloud can_use_sms_gateway can_manage_angebote
    externe_ag_leitung => can_write_messages can_create_polls can_create_events can_use_mailing_lists can_use_nextcloud can_use_sms_gateway can_manage_angebote
    schueler => can_receive_messages can_use_nextcloud
    sv => can_write_messages can_create_polls can_use_mailing_lists can_create_events unterstufenparty
    technikteam => can_write_messages can_book_tablets can_create_polls can_use_mailing_lists can_create_events can_manage_tablets can_manage_tech_problems can_report_tech_problems can_see_all_timetables
    admin => can_upload_files can_book_tablets can_manage_news can_manage_monitors can_manage_tablets can_manage_tech_problems can_report_tech_problems can_open_project_wifi sv_admin sv_editor unterstufenparty
    schulbuchverein => can_use_mailing_lists can_use_nextcloud can_use_sms_gateway
    technikamt => can_report_tech_problems
    developer => can_manage_project_wifi_access can_open_project_wifi
    gev => can_create_polls can_create_events can_use_mailing_lists can_use_nextcloud can_use_sms_gateway
    sv_admin => sv_editor
END_OF_STRING
